source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

target 'Tryouts_Example' do
  pod "Tryouts", :path => "../"

  pod 'PureLayout'
end

target 'Tryouts_Tests' do
  pod "Tryouts", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
